using System;

namespace LtiCalculation
{
    public class ExecutiveReportingInfo
    {
        #region //-------------------------- DataCapture.PersonFiscalYear 
        public int? PersonFiscalYearId { get; set; }
        public string Name { get; set; }
        public int? GenderId { get; set; }
        public int? Age { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public int? PersonFiscalYearRegionId { get; set; }
        public string JobTitle { get; set; }
        public int? JobRoleId { get; set; }
        public DateTime? DateOfHire { get; set; }
        public DateTime? DateAssignedToCurrentRole { get; set; }
        public DateTime? DateOfLeaving { get; set; }
        public int? Rank { get; set; }
        public int? IncumbentStatusId { get; set; }
        public string GeneralNotes { get; set; }
        #endregion

        #region //-------------------------- DataCapture.Executive
        public int Id { get; set; }
        public int? ExecutiveRegionId { get; set; }
        public int? AdditionalJobRoleId { get; set; }
        public bool? IsDirector { get; set; }
        public int? BusinessUnitRevenueCurrencyId { get; set; }
        public decimal? BusinessUnitRevenue { get; set; }
        public decimal? NumberOfMonthsServed { get; set; }
        public int? CountryOfOriginId { get; set; }
        public decimal? ExecutiveSctSalary { get; set; }
        public decimal? ExecutiveAnnualBaseSalaryAmount { get; set; }
        public int? ExecutiveDirectorRoleId { get; set; }
        public DateTime? DateOfBoardAppointment { get; set; }
        public int? DirectorTypeId { get; set; }
        public string JobChangeNotes { get; set; }
        public decimal? CEOTenureYears { get; set; }
        public int? FounderTypeId { get; set; }
        public bool? HasEmploymentAgreement { get; set; }
        public int? TerminationTypeId { get; set; }
        public int? JobFunctionId { get; set; }
        public string Responsibility { get; set; }
        public int? EmploymentStatusId { get; set; }
        public string BusinessUnitName { get; set; }
        #endregion

        #region //-------------------------- DataCapture.SummaryCompensation   
        public int? SummaryCompensationId { get; set; }
        public int? SummaryCompensationRegionId { get; set; }
        public decimal? AccumulatedPensionValue { get; set; }
        public decimal? AllOtherComp { get; set; }
        public decimal? SummaryCompensationSctSalary { get; set; }
        public decimal? Bonus { get; set; }
        public decimal? ChangeInPension { get; set; }
        public decimal? ChangeInPensionNQDCEarnings { get; set; }
        public decimal? ForwardLookingBonusPercent { get; set; }
        public decimal? ForwardLookingSalaryRate { get; set; }
        public decimal? FYEBonusPercent { get; set; }
        public decimal? FYESalary { get; set; }
        public decimal? LongTermPortionOfNEIPCompensation { get; set; }
        public decimal? NonEquityIncentivePlanPayouts { get; set; }
        public decimal? NQDCEarnings { get; set; }
        public decimal? NQDCFYEBalance { get; set; }
        public decimal? OptionAwardsExpense { get; set; }
        public decimal? OptionsExercisableWithin60DaysOfProxy { get; set; }
        public decimal? SharesHeld { get; set; }
        public decimal? ShortTermPortionOfNEIPCompensation { get; set; }
        public decimal? SpecialBonus { get; set; }
        public decimal? StockAwardsExpense { get; set; }
        public decimal? TotalCompensationReported { get; set; }
        public string TransactionComment { get; set; }
        public int? SpecialBonusTypeId { get; set; }
        public int? AnnualBaseSalaryCurrencyId { get; set; }
        public decimal? SummaryCompensationAnnualBaseSalaryAmount { get; set; }
        public bool? AnnualBaseSalaryIsProRated { get; set; }
        public int? AnnualBaseSalaryFYECurrencyId { get; set; }
        public decimal? AnnualBaseSalaryFYEAmount { get; set; }
        public decimal? AnnualBaseSalaryPercentIncrease { get; set; }
        public int? AnnualBaseSalaryFLCurrencyId { get; set; }
        public decimal? AnnualBaseSalaryFLAmount { get; set; }
        public decimal? AnnualBaseSalaryFLPercentIncrease { get; set; }
        public int? AnnualBaseSalaryFLIncreaseTypeId { get; set; }
        public string AnnualBaseSalaryFLIncreaseNotes { get; set; }
        public bool? BoardFeeIsReported { get; set; }
        public int? BoardFeeCurrencyId { get; set; }
        public decimal? BoardFeeAmount { get; set; }
        public decimal? BoardFeeSubsidiaryBoardAmount { get; set; }
        public bool? IsRegulatoryPayReported { get; set; }
        public int? RegulatoryPayCurrencyId { get; set; }
        public decimal? RegulatoryFixedPayAllowance { get; set; }
        public decimal? RegulatoryFixedPayTotal { get; set; }
        public int? RegulatoryPayFLCurrencyId { get; set; }
        public decimal? RegulatoryFixedPayAllowanceFL { get; set; }
        public decimal? RegulatoryFixedPayTotalFL { get; set; }
        public decimal? AnnualBonusTargetPercent { get; set; }
        public decimal? AnnualBonusMaxPercent { get; set; }
        public decimal? AnnualBonusFLTargetPercent { get; set; }
        public decimal? AnnualBonusFLMaxPercent { get; set; }
        public int? AnnualBonusCurrencyId { get; set; }
        public decimal? AnnualBonusCashPaymentImmediate { get; set; }
        public decimal? AnnualBonusCashPaymentMultiYear { get; set; }
        public decimal? AnnualBonusCashPaymentDeferredWithConditions { get; set; }
        public decimal? AnnualBonusCashPaymentDeferredWithoutConditions { get; set; }
        public decimal? AnnualBonusSharesPaymentImmediate { get; set; }
        public decimal? AnnualBonusSharesPaymentDeferredWithConditions { get; set; }
        public decimal? AnnualBonusSharesPaymentDeferredWithoutConditions { get; set; }
        public decimal? AnnualBonusTotalAmount { get; set; }
        public decimal? AnnualBonusTotalPaidImmediately { get; set; }
        public decimal? AnnualBonusTotalDeferred { get; set; }
        public decimal? AnnualBonusPercentCompulsorilyDeferred { get; set; }
        public decimal? AnnualBonusPercentVoluntaryDeferred { get; set; }
        public bool? AnnualBonusHasDeferralPerformanceCondition { get; set; }
        public decimal? AnnualBonusDeferralLTIValuationFactor { get; set; }
        public decimal? AnnualBonusPreviousFYAmount { get; set; }
        public int? AnnualBonusDeferredVestingCurrencyId { get; set; }
        public decimal? AnnualBonusDeferredVestingAmount { get; set; }
        public int? LTIEligibilityTypeId { get; set; }
        public int? LTIAwardFaceValueCurrencyId { get; set; }
        public decimal? LTIAwardFaceValueAmount { get; set; }
        public int? LTIVestingValueCurrencyId { get; set; }
        public decimal? LTIVestingValueAmount { get; set; }
        public int? LTIAwardFairValueCurrencyId { get; set; }
        public decimal? LTIAwardFairValueAmount { get; set; }
        public int? LTIAwardOtherValueCurrencyId { get; set; }
        public decimal? LTIAwardOtherValueAmount { get; set; }
        public int? VariablePayCurrencyId { get; set; }
        public decimal? VariablePayAmount { get; set; }
        public int? PensionProvisionTypeId { get; set; }
        public int? PensionCurrencyId { get; set; }
        public decimal? PensionAmount { get; set; }
        public decimal? PensionFLPercent { get; set; }
        public string PensionNotes { get; set; }
        public int? BenefitsPerksCurrencyId { get; set; }
        public decimal? BenefitsPerksAmount { get; set; }
        public string BenefitsPerksDescription { get; set; }
        public int? OtherExceptionalCurrencyId { get; set; }
        public decimal? OtherExceptionalVestedRealized { get; set; }
        public decimal? OtherExceptionalGranted { get; set; }
        public string OtherExceptionalDescription { get; set; }
        public int? TotalCompCurrencyId { get; set; }
        public decimal? TotalCompAmount { get; set; }
        public decimal? TotalCompPreviousFYAmount { get; set; }
        public bool? HasShareOwnershipGuideline { get; set; }
        public decimal? ShareholdingGuidelineSharesHeld { get; set; }
        public decimal? ShareholdingGuidelinePercentOfBase { get; set; }
        public decimal? ShareholdingGuidelineNumberOfShares { get; set; }
        public bool? ShareholdingGuidelineIsMet { get; set; }
        public string ShareholdingGuidelineNotes { get; set; }
        public string PayRelatedNotes { get; set; }
        public string PayRelatedFLNotes { get; set; }
        public int? AnnualBonusEligibilityTypeId { get; set; }
        public int? AnnualBonusEligibilityTypeFLId { get; set; }
        public int? AnnualBonusTotalCurrencyId { get; set; }
        public int? AnnualBonusDeferralSchemeId { get; set; }
        public int? LTIEligibilityTypeFLId { get; set; }
        public string InternalNotes { get; set; }
        public int? CurrencyId { get; set; }
        public bool? FeesIsProRated { get; set; }
        public decimal? Fees { get; set; }
        public bool? AnnualBaseSalaryAmountIsProrated { get; set; }
        public bool? SalaryAllowancesAndBenefitsIsProrated { get; set; }
        public decimal? SalaryAllowancesAndBenefits { get; set; }
        public int? AllowanceBenefitDataSeparableId { get; set; }
        public string AllowanceBenefitDataNotes { get; set; }
        public bool? AnnualIncentivesNonDeferredIsProrated { get; set; }
        public decimal? AnnualIncentivesNonDeferred { get; set; }
        public bool? AnnualIncentivesDeferredIsProrated { get; set; }
        public decimal? AnnualIncentivesDeferred { get; set; }
        public string AnnualIncentivesNotes { get; set; }
        public bool? LTIExpensesIsProRated { get; set; }
        public int? LTIExpensesCurrencyId { get; set; }
        public decimal? LTIExpenses { get; set; }
        public bool? LTIAwardFairValueAmountIsProRated { get; set; }
        public bool? PensionAndRetirementBenefitsIsProrated { get; set; }
        public decimal? PensionAndRetirementBenefits { get; set; }
        public bool? TotalCashCompAmountIsProRated { get; set; }
        public decimal? TotalCashCompAmount { get; set; }
        public bool? TotalCompAmountIsProRated { get; set; }
        public int? TotalCashCompCurrencyId { get; set; }
        public decimal? PolicySalary { get; set; }
        public decimal? TargetBonusPercent { get; set; }
        public decimal? MaximumBonusPercent { get; set; }
        public decimal? LtiAccountingValue { get; set; }
        public decimal? AnnualizedSalary { get; set; }
        public decimal? LtiTargetValue { get; set; }
        public decimal? LtiSctTotal { get; set; }
        public int? LongTermPortionOfNEIPCompensationCurrencyId { get; set; }
        public int? OptionAwardsExpenseCurrencyId { get; set; }
        public int? ShortTermPortionOfNEIPCompensationCurrencyId { get; set; }
        public int? SpecialBonusCurrencyId { get; set; }
        public int? StockAwardsExpenseCurrencyId { get; set; }
        public decimal? Benefits { get; set; }
        public decimal? SuperAnnuation { get; set; }
        public decimal? OtherBenefits { get; set; }
        public decimal? AccruedLeave { get; set; }
        public int? STIEligibilityTypeId { get; set; }
        public decimal? StiCash { get; set; }
        public decimal? StiDeferralValue { get; set; }
        public decimal? Target { get; set; }
        public decimal? Maximum { get; set; }
        public int? LTICurrencyId { get; set; }
        public decimal? TotalReportedLTIValue { get; set; }
        public decimal? FairValueLTI { get; set; }
        public string Notes { get; set; }
        #endregion

        #region //-------------------------- OptionsExercisedAndStockVested
        public int? OptionsExercisedAndStockVestedId { get; set; }
        public decimal? SharesAcquiredOnExerciseOfOptions { get; set; }
        public decimal? ValueRealizedOnExercise { get; set; }
        public decimal? SharesAcquiredOnVestingOfStock { get; set; }
        public decimal? ValueRealizedOnVesting { get; set; }
        public string OptionsExercisedAndStockVestedTransactionComment { get; set; }
        public int? OptionsExercisedAndStockVestedRegionId { get; set; }
        public decimal? OptionAwardsValueVested { get; set; }
        public decimal? StockAwardsValueRealizedOnVesting { get; set; }
        public decimal? AnnualBonusPayout { get; set; }
        #endregion

        #region //-------------------------- PersonFiscalYear Descriptions
        public string PersonFiscalYearGenderCode { get; set; }
        public string PersonFiscalYearGenderName { get; set; }
        public string PersonFiscalYearRegionCode { get; set; }
        public string PersonFiscalYearRegionName { get; set; }
        public string PersonFiscalYearJobRoleCode { get; set; }
        public string PersonFiscalYearJobRoleName { get; set; }
        public string PersonFiscalYearIncumbentStatusCode { get; set; }
        public string PersonFiscalYearIncumbentStatusName { get; set; }
        #endregion

        #region //-------------------------- Executive Description
        public string ExecutiveRegionCode { get; set; }
        public string ExecutiveRegionName { get; set; }
        public string ExecutiveAdditionalJobRoleCode { get; set; }
        public string ExecutiveAdditionalJobRoleName { get; set; }
        public string ExecutiveBusinessUnitRevenueCurrencyCode { get; set; }
        public string ExecutiveBusinessUnitRevenueCurrencyName { get; set; }
        public string ExecutiveCountryOfOriginCode { get; set; }
        public string ExecutiveCountryOfOriginName { get; set; }
        public string ExecutiveDirectorRoleCode { get; set; }
        public string ExecutiveDirectorRoleName { get; set; }
        public string ExecutiveDirectorTypeCode { get; set; }
        public string ExecutiveDirectorTypeName { get; set; }
        public string ExecutiveFounderTypeCode { get; set; }
        public string ExecutiveFounderTypeName { get; set; }
        public string ExecutiveTerminationTypeCode { get; set; }
        public string ExecutiveTerminationTypeName { get; set; }
        public string ExecutiveJobFunctionCode { get; set; }
        public string ExecutiveJobFunctionName { get; set; }
        public string ExecutiveEmploymentStatusCode { get; set; }
        public string ExecutiveEmploymentStatusName { get; set; }
        #endregion

        #region //-------------------------- SummaryCompensation Description
        public string SCRegionCode { get; set; }
        public string SCRegionName { get; set; }
        public string SCSpecialBonusTypeCode { get; set; }
        public string SCSpecialBonusTypeName { get; set; }
        public string SCSpecialBonusCurrencyCode { get; set; }
        public string SCSpecialBonusCurrencyName { get; set; }
        public string SCAnnualBaseSalaryCurrencyCode { get; set; }
        public string SCAnnualBaseSalaryCurrencyName { get; set; }
        public string SCAnnualBaseSalaryFYECurrencyCode { get; set; }
        public string SCAnnualBaseSalaryFYECurrencyName { get; set; }
        public string SCAnnualBaseSalaryFLCurrencyCode { get; set; }
        public string SCAnnualBaseSalaryFLCurrencyName { get; set; }
        public string SCAnnualBaseSalaryFLIncreaseTypeCode { get; set; }
        public string SCAnnualBaseSalaryFLIncreaseTypeName { get; set; }
        public string SCBoardFeeCurrencyCode { get; set; }
        public string SCBoardFeeCurrencyName { get; set; }
        public string SCRegulatoryPayCurrencyCode { get; set; }
        public string SCRegulatoryPayCurrencyName { get; set; }
        public string SCRegulatoryPayFLCurrencyCode { get; set; }
        public string SCRegulatoryPayFLCurrencyName { get; set; }
        public string SCAnnualBonusCurrencyCode { get; set; }
        public string SCAnnualBonusCurrencyName { get; set; }
        public string SCAnnualBonusDeferredVestingCurrencyCode { get; set; }
        public string SCAnnualBonusDeferredVestingCurrencyName { get; set; }
        public string SCLTIEligibilityTypeCode { get; set; }
        public string SCLTIEligibilityTypeName { get; set; }
        public string SCLTIAwardFaceValueCurrencyCode { get; set; }
        public string SCLTIAwardFaceValueCurrencyName { get; set; }
        public string SCLTIVestingValueCurrencyCode { get; set; }
        public string SCLTIVestingValueCurrencyName { get; set; }
        public string SCLTIAwardFairValueCurrencyCode { get; set; }
        public string SCLTIAwardFairValueCurrencyName { get; set; }
        public string SCLTIAwardOtherValueCurrencyCode { get; set; }
        public string SCLTIAwardOtherValueCurrencyName { get; set; }
        public string SCVariablePayCurrencyCode { get; set; }
        public string SCVariablePayCurrencyName { get; set; }
        public string SCPensionProvisionTypeCode { get; set; }
        public string SCPensionProvisionTypeName { get; set; }
        public string SCPensionCurrencyCode { get; set; }
        public string SCPensionCurrencyName { get; set; }
        public string SCBenefitsPerksCurrencyCode { get; set; }
        public string SCBenefitsPerksCurrencyName { get; set; }
        public string SCOtherExceptionalCurrencyCode { get; set; }
        public string SCOtherExceptionalCurrencyName { get; set; }
        public string SCTotalCompCurrencyCode { get; set; }
        public string SCTotalCompCurrencyName { get; set; }
        public string SCAnnualBonusEligibilityTypeCode { get; set; }
        public string SCAnnualBonusEligibilityTypeName { get; set; }
        public string SCAnnualBonusEligibilityTypeFLCode { get; set; }
        public string SCAnnualBonusEligibilityTypeFLName { get; set; }
        public string SCAnnualBonusTotalCurrencyCode { get; set; }
        public string SCAnnualBonusTotalCurrencyName { get; set; }
        public string SCAnnualBonusDeferralSchemeCode { get; set; }
        public string SCAnnualBonusDeferralSchemeName { get; set; }
        public string SCLTIEligibilityTypeFLCode { get; set; }
        public string SCLTIEligibilityTypeFLName { get; set; }
        public string SCCurrencyCode { get; set; }
        public string SCCurrencyName { get; set; }
        public string SCAllowanceBenefitDataSeparableCode { get; set; }
        public string SCAllowanceBenefitDataSeparableName { get; set; }
        public string SCLTIExpensesCurrencyCode { get; set; }
        public string SCLTIExpensesCurrencyName { get; set; }
        public string SCTotalCashCompCurrencyCode { get; set; }
        public string SCTotalCashCompCurrencyName { get; set; }
        public string SCLongTermPortionOfNEIPCompensationCurrencyCode { get; set; }
        public string SCLongTermPortionOfNEIPCompensationCurrencyName { get; set; }
        public string SCOptionAwardsExpenseCurrencyCode { get; set; }
        public string SCOptionAwardsExpenseCurrencyName { get; set; }
        public string SCShortTermPortionOfNEIPCompensationCurrencyCode { get; set; }
        public string SCShortTermPortionOfNEIPCompensationCurrencyName { get; set; }
        public string SCStockAwardsExpenseCurrencyCode { get; set; }
        public string SCStockAwardsExpenseCurrencyName { get; set; }
        public string SCSTIEligibilityTypeCode { get; set; }
        public string SCSTIEligibilityTypeName { get; set; }
        public string SCLTICurrencyCode { get; set; }
        public string SCLTICurrencyName { get; set; }
        public int CompanyPayRank { get; set; }
        #endregion
    }
}